asdf_optional_dependencies:
  # Erlang
  - automake
  - autoconf
  - build-essential
  - libreadline-dev
  - libncurses-dev
  - libssl-dev
  - libyaml-dev
  - libxslt-dev
  - libffi-dev
  - libtool
  - unzip

  # Node.js
  - gpg

gpg_pubring_file: pubring.kbx

ansible_build_deps:
  - python-pip
