# Install Elixir deploy-template
#
# Run setup tasks, e.g. installing packages and creating directories. Run this from an admin user with sudo.
#
# ansible-playbook -u $USER -v -l web-servers playbooks/deploy-template.yml --skip-tags deploy -D
#
# Deploy the code. Run this from the app user account on a dev machine.
#
# ansible-playbook -u deploy -v -l web-servers playbooks/deploy-template.yml --tags deploy --extra-vars ansible_become=false -D
#

- hosts: '*'
  become: true
  vars:
    # This could be your organization or the overall project if you have more than one app
    org: myorg
    # The external name of the app, used to name directories and the systemd process
    app_name: deploy-template
    # The internal "Elixir" name of the app, used to by Distillery to name directories
    app_name_code: deploy_template
    # OS user that the app runs under
    app_user: foo
    # OS group that the app runs under
    app_group: foo
    # Port that Phoenix listens on
    app_http_listen_port: 4001
    # See roles/deploy-template/defaults/main.yml for all the options
  roles:
    - deploy-template
