# Install Elixir deploy-template
#
# Run setup tasks, e.g. installing packages and creating directories. Run this from an admin user with sudo.
#
# ansible-playbook -u $USER -v -l web-servers playbooks/deploy-template.yml --skip-tags deploy -D
#
# Deploy the code. Run this from the app user account on a dev machine.
#
# ansible-playbook -u deploy -v -l web-servers playbooks/deploy-template.yml --tags deploy --extra-vars ansible_become=false -D
#

- hosts: '*'
  become: true
  vars:
    app_user: foo
    app_group: foo
    app_http_listen_port: 4001
    app_restart_method: touch
  roles:
    - deploy-template
